sodu: required
services:
  - docker

before_install:
  - docker build -t trishten/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true trishten/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "react-sample-app"
  env: "Reactsampleapp-env"
  buket_name: "elasticbeanstalk-us-east-1-258445496998"
  bucket_path: "react-sample-app"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"